// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TheHorselessNewspaper.Schemas.ContentModel.ContentEntities;

#nullable disable

namespace TheHorselessNewspaper.Schemas.ContentModel.ContentEntities.Configurations
{
    public partial class NavigationMenuConfiguration : IEntityTypeConfiguration<NavigationMenu>
    {
        public void Configure(EntityTypeBuilder<NavigationMenu> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasMany(d => d.Children)
                .WithMany(p => p.Parents)
                .UsingEntity<Dictionary<string, object>>(
                    "NavigationMenuHierarchy",
                    l => l.HasOne<NavigationMenu>().WithMany().HasForeignKey("Children_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NavigationMenuHierarchy_NavigationMenu"),
                    r => r.HasOne<NavigationMenu>().WithMany().HasForeignKey("Parents_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NavigationMenuHierarchy_Children"),
                    j =>
                    {
                        j.HasKey("Children_Id", "Parents_Id");

                        j.ToTable("NavigationMenuHierarchy");

                        j.HasIndex(new[] { "Parents_Id" }, "IX_FK_NavigationMenuHierarchy_Children");
                    });

            entity.HasMany(d => d.Parents)
                .WithMany(p => p.Children)
                .UsingEntity<Dictionary<string, object>>(
                    "NavigationMenuHierarchy",
                    l => l.HasOne<NavigationMenu>().WithMany().HasForeignKey("Parents_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NavigationMenuHierarchy_Children"),
                    r => r.HasOne<NavigationMenu>().WithMany().HasForeignKey("Children_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NavigationMenuHierarchy_NavigationMenu"),
                    j =>
                    {
                        j.HasKey("Children_Id", "Parents_Id");

                        j.ToTable("NavigationMenuHierarchy");

                        j.HasIndex(new[] { "Parents_Id" }, "IX_FK_NavigationMenuHierarchy_Children");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NavigationMenu> entity);
    }
}
