// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TheHorselessNewspaper.Schemas.ContentModel.ContentEntities;

#nullable disable

namespace TheHorselessNewspaper.Schemas.ContentModel.ContentEntities.Configurations
{
    public partial class TaxonomyConfiguration : IEntityTypeConfiguration<Taxonomy>
    {
        public void Configure(EntityTypeBuilder<Taxonomy> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasMany(d => d.ContentCollections)
                .WithMany(p => p.Taxonomies)
                .UsingEntity<Dictionary<string, object>>(
                    "ContentCollectionTaxonomy",
                    l => l.HasOne<ContentCollection>().WithMany().HasForeignKey("ContentCollections_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ContentCollectionTaxonomies_ContentCollection"),
                    r => r.HasOne<Taxonomy>().WithMany().HasForeignKey("Taxonomies_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ContentCollectionTaxonomies_Taxonomy"),
                    j =>
                    {
                        j.HasKey("Taxonomies_Id", "ContentCollections_Id");

                        j.ToTable("ContentCollectionTaxonomies");

                        j.HasIndex(new[] { "ContentCollections_Id" }, "IX_FK_ContentCollectionTaxonomies_ContentCollection");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Taxonomy> entity);
    }
}
