/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostingEntitiesACEPermission } from './hostingEntitiesACEPermission';
import { HostingEntitiesPrincipal } from './hostingEntitiesPrincipal';
import { HostingEntitiesTenant } from './hostingEntitiesTenant';
import { HostingEntitiesACEPermissionScope } from './hostingEntitiesACEPermissionScope';
import { HostingEntitiesACEPermissionType } from './hostingEntitiesACEPermissionType';


export interface HostingEntitiesAccessControlEntry { 
    Scope?: HostingEntitiesACEPermissionScope;
    Permission?: HostingEntitiesACEPermission;
    PermissionType?: HostingEntitiesACEPermissionType;
    Timestamp?: string | null;
    UpdatedAt?: string | null;
    Id?: string;
    DisplayName?: string | null;
    ObjectId?: string | null;
    IsSoftDeleted?: boolean | null;
    CreatedAt?: string | null;
    IsActive?: boolean | null;
    AccessControlEntries?: Array<HostingEntitiesAccessControlEntry> | null;
    Owners?: Array<HostingEntitiesPrincipal> | null;
    SubjectAccessControlEntries?: Array<HostingEntitiesAccessControlEntry> | null;
    SubjectPrincipals?: Array<HostingEntitiesPrincipal> | null;
    SubjectTenants?: Array<HostingEntitiesTenant> | null;
}

