/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostingEntitiesAccessControlEntry } from './hostingEntitiesAccessControlEntry';
import { HostingEntitiesPrincipal } from './hostingEntitiesPrincipal';
import { HostingEntitiesTenantInfo } from './hostingEntitiesTenantInfo';


export interface HostingEntitiesKeyCloakConfiguration { 
    AccessControlEntries?: Array<HostingEntitiesAccessControlEntry> | null;
    Owners?: Array<HostingEntitiesPrincipal> | null;
    IsSoftDeleted?: boolean | null;
    Timestamp?: string | null;
    UpdatedAt?: string | null;
    Id?: string;
    DisplayName?: string | null;
    Authority?: string | null;
    Realm?: string | null;
    ObjectId?: string | null;
    CreatedAt?: string | null;
    Iss?: string | null;
    Aud?: string | null;
    TenantInfoId?: string | null;
    TenantInfo?: HostingEntitiesTenantInfo;
}

