/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostingEntitiesAccessControlEntry } from './hostingEntitiesAccessControlEntry';
import { HostingEntitiesTenant } from './hostingEntitiesTenant';


export interface HostingEntitiesPrincipal { 
    UPN?: string | null;
    Email?: string | null;
    PreferredUserName?: string | null;
    Timestamp?: string | null;
    UpdatedAt?: string | null;
    Id?: string;
    DisplayName?: string | null;
    ObjectId?: string | null;
    IsSoftDeleted?: boolean | null;
    CreatedAt?: string | null;
    Iss?: string | null;
    Aud?: string | null;
    Sub?: string | null;
    AccessControlEntries?: Array<HostingEntitiesAccessControlEntry> | null;
    OwnedAccessControlEntries?: Array<HostingEntitiesAccessControlEntry> | null;
    OwnedPrincipals?: Array<HostingEntitiesPrincipal> | null;
    OwnedTenants?: Array<HostingEntitiesTenant> | null;
    Owners?: Array<HostingEntitiesPrincipal> | null;
    TenantAccounts?: Array<HostingEntitiesTenant> | null;
}

