# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - mrgncy
  
pool:
    name: Default
  
steps:
  - powershell: |
      Write-Host $(Build.SourcesDirectory)
  
  - task: PowerShell@2
    displayName: 'start mssqllocaldb'
    inputs:
      targetType: 'inline'
      script: 'sqllocaldb start mssqllocaldb'  

  - task: PowerShell@2
    displayName: 'set git safe'
    inputs:
      targetType: 'inline'
      script: 'git config --global --add safe.directory $(Build.SourcesDirectory)'  

  - checkout: self

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: src/entities/Model.Core.Taxa/Model.Core.Taxa.sln
      vstsFeed: '155346c4-4c3d-4269-a624-e98408645b68/37532069-a755-46e5-9614-9bd2c3da7795'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: Model.Core.Taxa/Model.Core.Taxa.sln
      arguments: '--configuration $(BuildConfiguration)'
      workingDirectory: src/entities
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: Horseless.HostingModel.SmokeTests.csproj
      arguments: '--configuration $(BuildConfiguration)'
      workingDirectory: src/entities/Model.Core.Taxa/Horseless.HostingModel.SmokeTests
  
  