# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  containers:
  - container: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123
      MSSQL_PID: Express
trigger:
  - mrgncy
  
pool:
    name: Azure Pipelines
  
steps:
  - powershell: |
      Write-Host $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: 'set git safe'
    inputs:
      targetType: 'inline'
      script: 'git config --global --add safe.directory $(Build.SourcesDirectory)'  

  - checkout: self

  - task: MSBuild@1
    inputs:
      solution: 'Model.Core.Taxa/Model.Core.Taxa.sln'
      msbuildArchitecture: 'x64'
      configuration: '$(BuildConfiguration)'
      clean: true
      maximumCpuCount: true
      restoreNugetPackages: true
      logProjectEvents: true'
        
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: Horseless.HostingModel.SmokeTests.csproj
      arguments: '--configuration $(BuildConfiguration)'
      workingDirectory: src/entities/Model.Core.Taxa/Horseless.HostingModel.SmokeTests
  
  