// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheHorselessNewspaper.Schemas.ContentModel.ContentEntities
{
    public partial class FilesystemAsset
    {
        public FilesystemAsset()
        {
            HorselessContents = new HashSet<HorselessContent>();
        }

        public Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string ObjectId { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string Filename { get; set; }

        public virtual ICollection<HorselessContent> HorselessContents { get; set; }
    }
}