// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TheHorselessNewspaper.Schemas.ContentModel.ContentEntities
{
    public partial class JSONAsset
    {
        public JSONAsset()
        {
            MimeContents = new HashSet<MimeContent>();
        }

        public Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string ObjectId { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string JsonValue { get; set; }

        public virtual ICollection<MimeContent> MimeContents { get; set; }
    }
}