/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentEntitiesPrincipalClaimContainer } from './contentEntitiesPrincipalClaimContainer';
import { ContentEntitiesAccessControlEntry } from './contentEntitiesAccessControlEntry';
import { ContentEntitiesHorselessSession } from './contentEntitiesHorselessSession';
import { ContentEntitiesTenant } from './contentEntitiesTenant';


export interface ContentEntitiesPrincipal { 
    id?: string;
    displayName?: string | null;
    objectId?: string | null;
    isSoftDeleted?: boolean | null;
    createdAt?: string | null;
    iss?: string | null;
    aud?: string | null;
    sub?: string | null;
    horselessSessions?: Array<ContentEntitiesHorselessSession> | null;
    accessControlEntries?: Array<ContentEntitiesAccessControlEntry> | null;
    ownedAccessControlEntries?: Array<ContentEntitiesAccessControlEntry> | null;
    ownedHorselessSessions?: Array<ContentEntitiesHorselessSession> | null;
    ownedPrincipals?: Array<ContentEntitiesPrincipal> | null;
    ownedTenants?: Array<ContentEntitiesTenant> | null;
    owners?: Array<ContentEntitiesPrincipal> | null;
    tenantAccounts?: Array<ContentEntitiesTenant> | null;
    isAnonymous?: boolean;
    upn?: string | null;
    email?: string | null;
    preferredUserName?: string | null;
    timestamp?: string | null;
    principalClaimContainer?: ContentEntitiesPrincipalClaimContainer;
    updatedAt?: string | null;
}

