/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostingEntitiesAccessControlEntry } from './hostingEntitiesAccessControlEntry';
import { HostingEntitiesUriPath } from './hostingEntitiesUriPath';
import { HostingEntitiesPrincipal } from './hostingEntitiesPrincipal';
import { HostingEntitiesTenant } from './hostingEntitiesTenant';
import { HostingEntitiesHost } from './hostingEntitiesHost';


export interface HostingEntitiesRoutingDiscriminator { 
    accessControlList?: Array<HostingEntitiesAccessControlEntry> | null;
    owners?: Array<HostingEntitiesPrincipal> | null;
    isSoftDeleted?: boolean | null;
    id?: string;
    isActive?: boolean | null;
    objectId?: string | null;
    displayName?: string | null;
    createdAt?: string | null;
    tenantId?: string | null;
    tenant?: HostingEntitiesTenant;
    hosts?: Array<HostingEntitiesHost> | null;
    uriPaths?: Array<HostingEntitiesUriPath> | null;
}

