/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheHorselessNewspaper.CSharp.Rest.Api;
using TheHorselessNewspaper.CSharp.Rest.Model;
using TheHorselessNewspaper.CSharp.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TheHorselessNewspaper.CSharp.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing ContentEntitiesACEPermission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentEntitiesACEPermissionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentEntitiesACEPermission
        //private ContentEntitiesACEPermission instance;

        public ContentEntitiesACEPermissionTests()
        {
            // TODO uncomment below to create an instance of ContentEntitiesACEPermission
            //instance = new ContentEntitiesACEPermission();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentEntitiesACEPermission
        /// </summary>
        [Fact]
        public void ContentEntitiesACEPermissionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentEntitiesACEPermission
            //Assert.IsType<ContentEntitiesACEPermission>(instance);
        }



    }

}
