/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheHorselessNewspaper.CSharp.Rest.Api;
using TheHorselessNewspaper.CSharp.Rest.Model;
using TheHorselessNewspaper.CSharp.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TheHorselessNewspaper.CSharp.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing HostingEntitiesTenantIdentifierStrategyContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostingEntitiesTenantIdentifierStrategyContainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostingEntitiesTenantIdentifierStrategyContainer
        //private HostingEntitiesTenantIdentifierStrategyContainer instance;

        public HostingEntitiesTenantIdentifierStrategyContainerTests()
        {
            // TODO uncomment below to create an instance of HostingEntitiesTenantIdentifierStrategyContainer
            //instance = new HostingEntitiesTenantIdentifierStrategyContainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostingEntitiesTenantIdentifierStrategyContainer
        /// </summary>
        [Fact]
        public void HostingEntitiesTenantIdentifierStrategyContainerInstanceTest()
        {
            // TODO uncomment below to test "IsType" HostingEntitiesTenantIdentifierStrategyContainer
            //Assert.IsType<HostingEntitiesTenantIdentifierStrategyContainer>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TenantIdentifierStrategyName'
        /// </summary>
        [Fact]
        public void TenantIdentifierStrategyNameTest()
        {
            // TODO unit test for the property 'TenantIdentifierStrategyName'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'StrategyId'
        /// </summary>
        [Fact]
        public void StrategyIdTest()
        {
            // TODO unit test for the property 'StrategyId'
        }
        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Fact]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }

    }

}
