export * from './accessControlEntriesREST.service';
import { AccessControlEntriesRESTService } from './accessControlEntriesREST.service';
export * from './accessControlEntriesREST.serviceInterface';
export * from './clientConfiguration.service';
import { ClientConfigurationService } from './clientConfiguration.service';
export * from './clientConfiguration.serviceInterface';
export * from './contentCollectionREST.service';
import { ContentCollectionRESTService } from './contentCollectionREST.service';
export * from './contentCollectionREST.serviceInterface';
export * from './dynamicViewServer.service';
import { DynamicViewServerService } from './dynamicViewServer.service';
export * from './dynamicViewServer.serviceInterface';
export * from './filesystemAssetIngress.service';
import { FilesystemAssetIngressService } from './filesystemAssetIngress.service';
export * from './filesystemAssetIngress.serviceInterface';
export * from './filesystemAssetREST.service';
import { FilesystemAssetRESTService } from './filesystemAssetREST.service';
export * from './filesystemAssetREST.serviceInterface';
export * from './holonymREST.service';
import { HolonymRESTService } from './holonymREST.service';
export * from './holonymREST.serviceInterface';
export * from './horselessContentREST.service';
import { HorselessContentRESTService } from './horselessContentREST.service';
export * from './horselessContentREST.serviceInterface';
export * from './horselessSessionREST.service';
import { HorselessSessionRESTService } from './horselessSessionREST.service';
export * from './horselessSessionREST.serviceInterface';
export * from './horselessViewREST.service';
import { HorselessViewRESTService } from './horselessViewREST.service';
export * from './horselessViewREST.serviceInterface';
export * from './jSONAssetREST.service';
import { JSONAssetRESTService } from './jSONAssetREST.service';
export * from './jSONAssetREST.serviceInterface';
export * from './keycloakAuthentication.service';
import { KeycloakAuthenticationService } from './keycloakAuthentication.service';
export * from './keycloakAuthentication.serviceInterface';
export * from './meronymREST.service';
import { MeronymRESTService } from './meronymREST.service';
export * from './meronymREST.serviceInterface';
export * from './mimeTypeREST.service';
import { MimeTypeRESTService } from './mimeTypeREST.service';
export * from './mimeTypeREST.serviceInterface';
export * from './navigationMenuItemREST.service';
import { NavigationMenuItemRESTService } from './navigationMenuItemREST.service';
export * from './navigationMenuItemREST.serviceInterface';
export * from './navigationMenuREST.service';
import { NavigationMenuRESTService } from './navigationMenuREST.service';
export * from './navigationMenuREST.serviceInterface';
export * from './nugetPackageREST.service';
import { NugetPackageRESTService } from './nugetPackageREST.service';
export * from './nugetPackageREST.serviceInterface';
export * from './principalREST.service';
import { PrincipalRESTService } from './principalREST.service';
export * from './principalREST.serviceInterface';
export * from './publicationREST.service';
import { PublicationRESTService } from './publicationREST.service';
export * from './publicationREST.serviceInterface';
export * from './tenantInfoREST.service';
import { TenantInfoRESTService } from './tenantInfoREST.service';
export * from './tenantInfoREST.serviceInterface';
export * from './tenantREST.service';
import { TenantRESTService } from './tenantREST.service';
export * from './tenantREST.serviceInterface';
export * from './tenantRegistration.service';
import { TenantRegistrationService } from './tenantRegistration.service';
export * from './tenantRegistration.serviceInterface';
export const APIS = [AccessControlEntriesRESTService, ClientConfigurationService, ContentCollectionRESTService, DynamicViewServerService, FilesystemAssetIngressService, FilesystemAssetRESTService, HolonymRESTService, HorselessContentRESTService, HorselessSessionRESTService, HorselessViewRESTService, JSONAssetRESTService, KeycloakAuthenticationService, MeronymRESTService, MimeTypeRESTService, NavigationMenuItemRESTService, NavigationMenuRESTService, NugetPackageRESTService, PrincipalRESTService, PublicationRESTService, TenantInfoRESTService, TenantRESTService, TenantRegistrationService];
