/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContentEntitiesMeronym } from '../model/models';
import { MvcProblemDetails } from '../model/models';


import { HorselessConfiguration }                                     from '../configuration';



export interface MeronymRESTServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: HorselessConfiguration;

    /**
     * 
     * 
     * @param __tenant__ 
     * @param ContentEntitiesMeronym 
     */
    contentEntitiesMeronymRESTCreate(__tenant__: string, ContentEntitiesMeronym?: ContentEntitiesMeronym, extraHttpRequestParams?: any): Observable<ContentEntitiesMeronym>;

    /**
     * 
     * 
     * @param objectId 
     * @param __tenant__ 
     */
    contentEntitiesMeronymRESTGetByObjectId(objectId: string, __tenant__: string, extraHttpRequestParams?: any): Observable<ContentEntitiesMeronym>;

    /**
     * 
     * 
     * @param __tenant__ 
     * @param pageSize 
     * @param pageNumber 
     * @param pageCount 
     */
    contentEntitiesMeronymRESTGetByPageNumber(__tenant__: string, pageSize?: number, pageNumber?: number, pageCount?: number, extraHttpRequestParams?: any): Observable<Array<ContentEntitiesMeronym>>;

    /**
     * 
     * 
     * @param contentCollectionId 
     * @param __tenant__ 
     * @param ContentEntitiesMeronym 
     */
    contentEntitiesMeronymRESTUpdate(contentCollectionId: string, __tenant__: string, ContentEntitiesMeronym?: ContentEntitiesMeronym, extraHttpRequestParams?: any): Observable<ContentEntitiesMeronym>;

}
