export * from './contentCollectionREST.service';
import { ContentCollectionRESTService } from './contentCollectionREST.service';
export * from './filesystemAssetREST.service';
import { FilesystemAssetRESTService } from './filesystemAssetREST.service';
export * from './holonymREST.service';
import { HolonymRESTService } from './holonymREST.service';
export * from './horselessContentREST.service';
import { HorselessContentRESTService } from './horselessContentREST.service';
export * from './horselessSessionREST.service';
import { HorselessSessionRESTService } from './horselessSessionREST.service';
export * from './jSONAssetREST.service';
import { JSONAssetRESTService } from './jSONAssetREST.service';
export * from './keycloakAuthentication.service';
import { KeycloakAuthenticationService } from './keycloakAuthentication.service';
export * from './meronymREST.service';
import { MeronymRESTService } from './meronymREST.service';
export * from './mimeTypeREST.service';
import { MimeTypeRESTService } from './mimeTypeREST.service';
export * from './navigationMenuItemREST.service';
import { NavigationMenuItemRESTService } from './navigationMenuItemREST.service';
export * from './navigationMenuREST.service';
import { NavigationMenuRESTService } from './navigationMenuREST.service';
export * from './tenantInfoREST.service';
import { TenantInfoRESTService } from './tenantInfoREST.service';
export * from './tenantREST.service';
import { TenantRESTService } from './tenantREST.service';
export * from './tenantRegistration.service';
import { TenantRegistrationService } from './tenantRegistration.service';
export const APIS = [ContentCollectionRESTService, FilesystemAssetRESTService, HolonymRESTService, HorselessContentRESTService, HorselessSessionRESTService, JSONAssetRESTService, KeycloakAuthenticationService, MeronymRESTService, MimeTypeRESTService, NavigationMenuItemRESTService, NavigationMenuRESTService, TenantInfoRESTService, TenantRESTService, TenantRegistrationService];
