/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TheHorselessNewspaper.CSharp.Rest.Client;
using TheHorselessNewspaper.CSharp.Rest.Api;
// uncomment below to import models
//using TheHorselessNewspaper.CSharp.Rest.Model;

namespace TheHorselessNewspaper.CSharp.Rest.Test.Api
{
    /// <summary>
    ///  Class for testing HolonymRESTApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HolonymRESTApiTests : IDisposable
    {
        private HolonymRESTApi instance;

        public HolonymRESTApiTests()
        {
            instance = new HolonymRESTApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HolonymRESTApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' HolonymRESTApi
            //Assert.IsType<HolonymRESTApi>(instance);
        }

        /// <summary>
        /// Test HolonymRESTControllerCreate
        /// </summary>
        [Fact]
        public void HolonymRESTControllerCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ContentEntitiesHolonym? contentEntitiesHolonym = null;
            //var response = instance.HolonymRESTControllerCreate(contentEntitiesHolonym);
            //Assert.IsType<ContentEntitiesHolonym>(response);
        }

        /// <summary>
        /// Test HolonymRESTControllerGetByObjectId
        /// </summary>
        [Fact]
        public void HolonymRESTControllerGetByObjectIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string objectId = null;
            //var response = instance.HolonymRESTControllerGetByObjectId(objectId);
            //Assert.IsType<ContentEntitiesHolonym>(response);
        }

        /// <summary>
        /// Test HolonymRESTControllerUpdate
        /// </summary>
        [Fact]
        public void HolonymRESTControllerUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contentCollectionId = null;
            //ContentEntitiesHolonym? contentEntitiesHolonym = null;
            //var response = instance.HolonymRESTControllerUpdate(contentCollectionId, contentEntitiesHolonym);
            //Assert.IsType<ContentEntitiesHolonym>(response);
        }
    }
}
