/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TheHorselessNewspaper.CSharp.Rest.Client;
using TheHorselessNewspaper.CSharp.Rest.Api;
// uncomment below to import models
//using TheHorselessNewspaper.CSharp.Rest.Model;

namespace TheHorselessNewspaper.CSharp.Rest.Test.Api
{
    /// <summary>
    ///  Class for testing HorselessSessionRESTApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HorselessSessionRESTApiTests : IDisposable
    {
        private HorselessSessionRESTApi instance;

        public HorselessSessionRESTApiTests()
        {
            instance = new HorselessSessionRESTApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HorselessSessionRESTApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' HorselessSessionRESTApi
            //Assert.IsType<HorselessSessionRESTApi>(instance);
        }

        /// <summary>
        /// Test HorselessSessionRESTControllerCreate
        /// </summary>
        [Fact]
        public void HorselessSessionRESTControllerCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenant = null;
            //ContentEntitiesHorselessSession? contentEntitiesHorselessSession = null;
            //var response = instance.HorselessSessionRESTControllerCreate(tenant, contentEntitiesHorselessSession);
            //Assert.IsType<ContentEntitiesContentCollection>(response);
        }

        /// <summary>
        /// Test HorselessSessionRESTControllerGetByObjectId
        /// </summary>
        [Fact]
        public void HorselessSessionRESTControllerGetByObjectIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string objectId = null;
            //string tenant = null;
            //var response = instance.HorselessSessionRESTControllerGetByObjectId(objectId, tenant);
            //Assert.IsType<ContentEntitiesContentCollection>(response);
        }

        /// <summary>
        /// Test HorselessSessionRESTControllerUpdate
        /// </summary>
        [Fact]
        public void HorselessSessionRESTControllerUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contentCollectionId = null;
            //string tenant = null;
            //ContentEntitiesHorselessSession? contentEntitiesHorselessSession = null;
            //var response = instance.HorselessSessionRESTControllerUpdate(contentCollectionId, tenant, contentEntitiesHorselessSession);
            //Assert.IsType<ContentEntitiesContentCollection>(response);
        }
    }
}
