/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TheHorselessNewspaper.CSharp.Rest.Client;
using TheHorselessNewspaper.CSharp.Rest.Api;
// uncomment below to import models
//using TheHorselessNewspaper.CSharp.Rest.Model;

namespace TheHorselessNewspaper.CSharp.Rest.Test.Api
{
    /// <summary>
    ///  Class for testing NavigationMenuItemApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NavigationMenuItemApiTests : IDisposable
    {
        private NavigationMenuItemApi instance;

        public NavigationMenuItemApiTests()
        {
            instance = new NavigationMenuItemApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NavigationMenuItemApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NavigationMenuItemApi
            //Assert.IsType<NavigationMenuItemApi>(instance);
        }

        /// <summary>
        /// Test NavigationMenuItemControllerGet
        /// </summary>
        [Fact]
        public void NavigationMenuItemControllerGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NavigationMenuItemControllerGet();
            //Assert.IsType<List<ContentEntitiesNavigationMenuItem>>(response);
        }

        /// <summary>
        /// Test NavigationMenuItemControllerGet_0
        /// </summary>
        [Fact]
        public void NavigationMenuItemControllerGet_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NavigationMenuItemControllerGet_0();
            //Assert.IsType<List<ContentEntitiesNavigationMenuItem>>(response);
        }
    }
}
