/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TheHorselessNewspaper.CSharp.Rest.Client;
using TheHorselessNewspaper.CSharp.Rest.Api;
// uncomment below to import models
//using TheHorselessNewspaper.CSharp.Rest.Model;

namespace TheHorselessNewspaper.CSharp.Rest.Test.Api
{
    /// <summary>
    ///  Class for testing TenantInfoRESTApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TenantInfoRESTApiTests : IDisposable
    {
        private TenantInfoRESTApi instance;

        public TenantInfoRESTApiTests()
        {
            instance = new TenantInfoRESTApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantInfoRESTApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TenantInfoRESTApi
            //Assert.IsType<TenantInfoRESTApi>(instance);
        }

        /// <summary>
        /// Test TenantInfoRESTControllerCreate
        /// </summary>
        [Fact]
        public void TenantInfoRESTControllerCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HostingEntitiesTenantInfo? hostingEntitiesTenantInfo = null;
            //var response = instance.TenantInfoRESTControllerCreate(hostingEntitiesTenantInfo);
            //Assert.IsType<HostingEntitiesTenantInfo>(response);
        }

        /// <summary>
        /// Test TenantInfoRESTControllerGetByObjectId
        /// </summary>
        [Fact]
        public void TenantInfoRESTControllerGetByObjectIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string objectId = null;
            //var response = instance.TenantInfoRESTControllerGetByObjectId(objectId);
            //Assert.IsType<HostingEntitiesTenantInfo>(response);
        }

        /// <summary>
        /// Test TenantInfoRESTControllerUpdate
        /// </summary>
        [Fact]
        public void TenantInfoRESTControllerUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string entityCollectionId = null;
            //HostingEntitiesTenantInfo? hostingEntitiesTenantInfo = null;
            //var response = instance.TenantInfoRESTControllerUpdate(entityCollectionId, hostingEntitiesTenantInfo);
            //Assert.IsType<HostingEntitiesTenantInfo>(response);
        }
    }
}
