/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using TheHorselessNewspaper.CSharp.Rest.Client;
using TheHorselessNewspaper.CSharp.Rest.Model;

namespace TheHorselessNewspaper.CSharp.Rest.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INavigationMenuRESTApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ContentEntitiesMIMEType</returns>
        ContentEntitiesMIMEType NavigationMenuRESTControllerCreate(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ApiResponse of ContentEntitiesMIMEType</returns>
        ApiResponse<ContentEntitiesMIMEType> NavigationMenuRESTControllerCreateWithHttpInfo(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <returns>ContentEntitiesMIMEType</returns>
        ContentEntitiesMIMEType NavigationMenuRESTControllerGetByObjectId(string objectId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <returns>ApiResponse of ContentEntitiesMIMEType</returns>
        ApiResponse<ContentEntitiesMIMEType> NavigationMenuRESTControllerGetByObjectIdWithHttpInfo(string objectId);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ContentEntitiesMIMEType</returns>
        ContentEntitiesMIMEType NavigationMenuRESTControllerUpdate(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ApiResponse of ContentEntitiesMIMEType</returns>
        ApiResponse<ContentEntitiesMIMEType> NavigationMenuRESTControllerUpdateWithHttpInfo(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INavigationMenuRESTApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ContentEntitiesMIMEType</returns>
        System.Threading.Tasks.Task<ContentEntitiesMIMEType> NavigationMenuRESTControllerCreateAsync(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ContentEntitiesMIMEType)</returns>
        System.Threading.Tasks.Task<ApiResponse<ContentEntitiesMIMEType>> NavigationMenuRESTControllerCreateWithHttpInfoAsync(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ContentEntitiesMIMEType</returns>
        System.Threading.Tasks.Task<ContentEntitiesMIMEType> NavigationMenuRESTControllerGetByObjectIdAsync(string objectId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ContentEntitiesMIMEType)</returns>
        System.Threading.Tasks.Task<ApiResponse<ContentEntitiesMIMEType>> NavigationMenuRESTControllerGetByObjectIdWithHttpInfoAsync(string objectId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ContentEntitiesMIMEType</returns>
        System.Threading.Tasks.Task<ContentEntitiesMIMEType> NavigationMenuRESTControllerUpdateAsync(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ContentEntitiesMIMEType)</returns>
        System.Threading.Tasks.Task<ApiResponse<ContentEntitiesMIMEType>> NavigationMenuRESTControllerUpdateWithHttpInfoAsync(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INavigationMenuRESTApi : INavigationMenuRESTApiSync, INavigationMenuRESTApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NavigationMenuRESTApi : INavigationMenuRESTApi
    {
        private TheHorselessNewspaper.CSharp.Rest.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationMenuRESTApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NavigationMenuRESTApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationMenuRESTApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NavigationMenuRESTApi(string basePath)
        {
            this.Configuration = TheHorselessNewspaper.CSharp.Rest.Client.Configuration.MergeConfigurations(
                TheHorselessNewspaper.CSharp.Rest.Client.GlobalConfiguration.Instance,
                new TheHorselessNewspaper.CSharp.Rest.Client.Configuration { BasePath = basePath }
            );
            this.Client = new TheHorselessNewspaper.CSharp.Rest.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TheHorselessNewspaper.CSharp.Rest.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = TheHorselessNewspaper.CSharp.Rest.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationMenuRESTApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NavigationMenuRESTApi(TheHorselessNewspaper.CSharp.Rest.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TheHorselessNewspaper.CSharp.Rest.Client.Configuration.MergeConfigurations(
                TheHorselessNewspaper.CSharp.Rest.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new TheHorselessNewspaper.CSharp.Rest.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TheHorselessNewspaper.CSharp.Rest.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = TheHorselessNewspaper.CSharp.Rest.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationMenuRESTApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public NavigationMenuRESTApi(TheHorselessNewspaper.CSharp.Rest.Client.ISynchronousClient client, TheHorselessNewspaper.CSharp.Rest.Client.IAsynchronousClient asyncClient, TheHorselessNewspaper.CSharp.Rest.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TheHorselessNewspaper.CSharp.Rest.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TheHorselessNewspaper.CSharp.Rest.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TheHorselessNewspaper.CSharp.Rest.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TheHorselessNewspaper.CSharp.Rest.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TheHorselessNewspaper.CSharp.Rest.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ContentEntitiesMIMEType</returns>
        public ContentEntitiesMIMEType NavigationMenuRESTControllerCreate(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?))
        {
            TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> localVarResponse = NavigationMenuRESTControllerCreateWithHttpInfo(contentEntitiesNavigationMenu);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ApiResponse of ContentEntitiesMIMEType</returns>
        public TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> NavigationMenuRESTControllerCreateWithHttpInfo(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?))
        {
            TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions localVarRequestOptions = new TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;odata.metadata=minimal;odata.streaming=true",
                "application/json;odata.metadata=minimal;odata.streaming=false",
                "application/json;odata.metadata=minimal",
                "application/json;odata.metadata=full;odata.streaming=true",
                "application/json;odata.metadata=full;odata.streaming=false",
                "application/json;odata.metadata=full",
                "application/json;odata.metadata=none;odata.streaming=true",
                "application/json;odata.metadata=none;odata.streaming=false",
                "application/json;odata.metadata=none",
                "application/json;odata.streaming=true",
                "application/json;odata.streaming=false",
                "application/json",
                "application/xml",
                "text/plain",
                "application/octet-stream",
                "text/json"
            };

            var localVarContentType = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = contentEntitiesNavigationMenu;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ContentEntitiesMIMEType>("/api/HorselessContentModelModel/NavigationMenu/Create", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("NavigationMenuRESTControllerCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ContentEntitiesMIMEType</returns>
        public async System.Threading.Tasks.Task<ContentEntitiesMIMEType> NavigationMenuRESTControllerCreateAsync(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> localVarResponse = await NavigationMenuRESTControllerCreateWithHttpInfoAsync(contentEntitiesNavigationMenu, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ContentEntitiesMIMEType)</returns>
        public async System.Threading.Tasks.Task<TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType>> NavigationMenuRESTControllerCreateWithHttpInfoAsync(ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions localVarRequestOptions = new TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;odata.metadata=minimal;odata.streaming=true",
                "application/json;odata.metadata=minimal;odata.streaming=false",
                "application/json;odata.metadata=minimal",
                "application/json;odata.metadata=full;odata.streaming=true",
                "application/json;odata.metadata=full;odata.streaming=false",
                "application/json;odata.metadata=full",
                "application/json;odata.metadata=none;odata.streaming=true",
                "application/json;odata.metadata=none;odata.streaming=false",
                "application/json;odata.metadata=none",
                "application/json;odata.streaming=true",
                "application/json;odata.streaming=false",
                "application/json",
                "application/xml",
                "text/plain",
                "application/octet-stream",
                "text/json"
            };

            var localVarContentType = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = contentEntitiesNavigationMenu;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ContentEntitiesMIMEType>("/api/HorselessContentModelModel/NavigationMenu/Create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("NavigationMenuRESTControllerCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <returns>ContentEntitiesMIMEType</returns>
        public ContentEntitiesMIMEType NavigationMenuRESTControllerGetByObjectId(string objectId)
        {
            TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> localVarResponse = NavigationMenuRESTControllerGetByObjectIdWithHttpInfo(objectId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <returns>ApiResponse of ContentEntitiesMIMEType</returns>
        public TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> NavigationMenuRESTControllerGetByObjectIdWithHttpInfo(string objectId)
        {
            // verify the required parameter 'objectId' is set
            if (objectId == null)
            {
                throw new TheHorselessNewspaper.CSharp.Rest.Client.ApiException(400, "Missing required parameter 'objectId' when calling NavigationMenuRESTApi->NavigationMenuRESTControllerGetByObjectId");
            }

            TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions localVarRequestOptions = new TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;odata.metadata=minimal;odata.streaming=true",
                "application/json;odata.metadata=minimal;odata.streaming=false",
                "application/json;odata.metadata=minimal",
                "application/json;odata.metadata=full;odata.streaming=true",
                "application/json;odata.metadata=full;odata.streaming=false",
                "application/json;odata.metadata=full",
                "application/json;odata.metadata=none;odata.streaming=true",
                "application/json;odata.metadata=none;odata.streaming=false",
                "application/json;odata.metadata=none",
                "application/json;odata.streaming=true",
                "application/json;odata.streaming=false",
                "application/json",
                "application/xml",
                "text/plain",
                "application/octet-stream",
                "text/json"
            };

            var localVarContentType = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("objectId", TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.ParameterToString(objectId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<ContentEntitiesMIMEType>("/api/HorselessContentModelModel/NavigationMenu/GetByObjectId", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("NavigationMenuRESTControllerGetByObjectId", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ContentEntitiesMIMEType</returns>
        public async System.Threading.Tasks.Task<ContentEntitiesMIMEType> NavigationMenuRESTControllerGetByObjectIdAsync(string objectId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> localVarResponse = await NavigationMenuRESTControllerGetByObjectIdWithHttpInfoAsync(objectId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="objectId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ContentEntitiesMIMEType)</returns>
        public async System.Threading.Tasks.Task<TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType>> NavigationMenuRESTControllerGetByObjectIdWithHttpInfoAsync(string objectId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'objectId' is set
            if (objectId == null)
            {
                throw new TheHorselessNewspaper.CSharp.Rest.Client.ApiException(400, "Missing required parameter 'objectId' when calling NavigationMenuRESTApi->NavigationMenuRESTControllerGetByObjectId");
            }


            TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions localVarRequestOptions = new TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;odata.metadata=minimal;odata.streaming=true",
                "application/json;odata.metadata=minimal;odata.streaming=false",
                "application/json;odata.metadata=minimal",
                "application/json;odata.metadata=full;odata.streaming=true",
                "application/json;odata.metadata=full;odata.streaming=false",
                "application/json;odata.metadata=full",
                "application/json;odata.metadata=none;odata.streaming=true",
                "application/json;odata.metadata=none;odata.streaming=false",
                "application/json;odata.metadata=none",
                "application/json;odata.streaming=true",
                "application/json;odata.streaming=false",
                "application/json",
                "application/xml",
                "text/plain",
                "application/octet-stream",
                "text/json"
            };

            var localVarContentType = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("objectId", TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.ParameterToString(objectId)); // path parameter


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ContentEntitiesMIMEType>("/api/HorselessContentModelModel/NavigationMenu/GetByObjectId", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("NavigationMenuRESTControllerGetByObjectId", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ContentEntitiesMIMEType</returns>
        public ContentEntitiesMIMEType NavigationMenuRESTControllerUpdate(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?))
        {
            TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> localVarResponse = NavigationMenuRESTControllerUpdateWithHttpInfo(contentCollectionId, contentEntitiesNavigationMenu);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <returns>ApiResponse of ContentEntitiesMIMEType</returns>
        public TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> NavigationMenuRESTControllerUpdateWithHttpInfo(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?))
        {
            // verify the required parameter 'contentCollectionId' is set
            if (contentCollectionId == null)
            {
                throw new TheHorselessNewspaper.CSharp.Rest.Client.ApiException(400, "Missing required parameter 'contentCollectionId' when calling NavigationMenuRESTApi->NavigationMenuRESTControllerUpdate");
            }

            TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions localVarRequestOptions = new TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;odata.metadata=minimal;odata.streaming=true",
                "application/json;odata.metadata=minimal;odata.streaming=false",
                "application/json;odata.metadata=minimal",
                "application/json;odata.metadata=full;odata.streaming=true",
                "application/json;odata.metadata=full;odata.streaming=false",
                "application/json;odata.metadata=full",
                "application/json;odata.metadata=none;odata.streaming=true",
                "application/json;odata.metadata=none;odata.streaming=false",
                "application/json;odata.metadata=none",
                "application/json;odata.streaming=true",
                "application/json;odata.streaming=false",
                "application/json",
                "application/xml",
                "text/plain",
                "application/octet-stream",
                "text/json"
            };

            var localVarContentType = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("contentCollectionId", TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.ParameterToString(contentCollectionId)); // path parameter
            localVarRequestOptions.Data = contentEntitiesNavigationMenu;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ContentEntitiesMIMEType>("/api/HorselessContentModelModel/NavigationMenu/Update/{contentCollectionId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("NavigationMenuRESTControllerUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ContentEntitiesMIMEType</returns>
        public async System.Threading.Tasks.Task<ContentEntitiesMIMEType> NavigationMenuRESTControllerUpdateAsync(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType> localVarResponse = await NavigationMenuRESTControllerUpdateWithHttpInfoAsync(contentCollectionId, contentEntitiesNavigationMenu, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="TheHorselessNewspaper.CSharp.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentCollectionId"></param>
        /// <param name="contentEntitiesNavigationMenu"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ContentEntitiesMIMEType)</returns>
        public async System.Threading.Tasks.Task<TheHorselessNewspaper.CSharp.Rest.Client.ApiResponse<ContentEntitiesMIMEType>> NavigationMenuRESTControllerUpdateWithHttpInfoAsync(string contentCollectionId, ContentEntitiesNavigationMenu? contentEntitiesNavigationMenu = default(ContentEntitiesNavigationMenu?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentCollectionId' is set
            if (contentCollectionId == null)
            {
                throw new TheHorselessNewspaper.CSharp.Rest.Client.ApiException(400, "Missing required parameter 'contentCollectionId' when calling NavigationMenuRESTApi->NavigationMenuRESTControllerUpdate");
            }


            TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions localVarRequestOptions = new TheHorselessNewspaper.CSharp.Rest.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;odata.metadata=minimal;odata.streaming=true",
                "application/json;odata.metadata=minimal;odata.streaming=false",
                "application/json;odata.metadata=minimal",
                "application/json;odata.metadata=full;odata.streaming=true",
                "application/json;odata.metadata=full;odata.streaming=false",
                "application/json;odata.metadata=full",
                "application/json;odata.metadata=none;odata.streaming=true",
                "application/json;odata.metadata=none;odata.streaming=false",
                "application/json;odata.metadata=none",
                "application/json;odata.streaming=true",
                "application/json;odata.streaming=false",
                "application/json",
                "application/xml",
                "text/plain",
                "application/octet-stream",
                "text/json"
            };

            var localVarContentType = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("contentCollectionId", TheHorselessNewspaper.CSharp.Rest.Client.ClientUtils.ParameterToString(contentCollectionId)); // path parameter
            localVarRequestOptions.Data = contentEntitiesNavigationMenu;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ContentEntitiesMIMEType>("/api/HorselessContentModelModel/NavigationMenu/Update/{contentCollectionId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("NavigationMenuRESTControllerUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
