// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheHorselessNewspaper.Schemas.HostingModel.HostingEntities
{
    public partial class Principal
    {
        public Principal()
        {
            AccessControlEntries = new HashSet<AccessControlEntry>();
        }

        public Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string ObjectId { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string Iss { get; set; }
        public string Aud { get; set; }
        public string Sub { get; set; }
        public Guid? TenantId { get; set; }

        public virtual Tenant Tenant { get; set; }

        public virtual ICollection<AccessControlEntry> AccessControlEntries { get; set; }
    }
}