// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TheHorselessNewspaper.Schemas.HostingModel.Entities
{
    internal partial class THLNPHostingContext : DbContext
    {
        public THLNPHostingContext()
        {
        }

        public THLNPHostingContext(DbContextOptions<THLNPHostingContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AccessControlEntry> AccessControlEntries { get; set; }
        public virtual DbSet<FilesystemAssetLocation> FilesystemAssetLocations { get; set; }
        public virtual DbSet<HorselessSession> HorselessSessions { get; set; }
        public virtual DbSet<Host> Hosts { get; set; }
        public virtual DbSet<KeyCloakConfiguration> KeyCloakConfigurations { get; set; }
        public virtual DbSet<NugetPackage> NugetPackages { get; set; }
        public virtual DbSet<Principal> Principals { get; set; }
        public virtual DbSet<RoutingDiscriminator> RoutingDiscriminators { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<TenantInfo> TenantInfos { get; set; }
        public virtual DbSet<UriPath> UriPaths { get; set; }
        public virtual DbSet<WebAPITenantInfo> WebAPITenantInfos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AccessControlEntry>(entity =>
            {
                entity.ToTable("AccessControlEntries", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();
            });

            modelBuilder.Entity<FilesystemAssetLocation>(entity =>
            {
                entity.ToTable("FilesystemAssetLocations", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            });

            modelBuilder.Entity<HorselessSession>(entity =>
            {
                entity.ToTable("HorselessSessions", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();
            });

            modelBuilder.Entity<Host>(entity =>
            {
                entity.ToTable("Hosts", "HostingModel");

                entity.HasIndex(e => e.RoutingDiscriminatorId, "IX_FK_RoutingDiscriminatorHost");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.HasOne(d => d.RoutingDiscriminator)
                    .WithMany(p => p.Hosts)
                    .HasForeignKey(d => d.RoutingDiscriminatorId)
                    .HasConstraintName("FK_RoutingDiscriminatorHost");
            });

            modelBuilder.Entity<KeyCloakConfiguration>(entity =>
            {
                entity.ToTable("KeyCloakConfigurations", "HostingModel");

                entity.HasIndex(e => e.TenantInfoId, "IX_FK_TenantInfoKeyCloakConfiguration");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.DisplayName).IsRequired();

                entity.HasOne(d => d.TenantInfo)
                    .WithMany(p => p.KeyCloakConfigurations)
                    .HasForeignKey(d => d.TenantInfoId)
                    .HasConstraintName("FK_TenantInfoKeyCloakConfiguration");
            });

            modelBuilder.Entity<NugetPackage>(entity =>
            {
                entity.ToTable("NugetPackages", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            });

            modelBuilder.Entity<Principal>(entity =>
            {
                entity.ToTable("Principals", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();

                entity.HasMany(d => d.Tenants)
                    .WithMany(p => p.Principals)
                    .UsingEntity<Dictionary<string, object>>(
                        "PrincipalTenant",
                        l => l.HasOne<Tenant>().WithMany().HasForeignKey("Tenants_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PrincipalTenant_Tenant"),
                        r => r.HasOne<Principal>().WithMany().HasForeignKey("Principals_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PrincipalTenant_Principal"),
                        j =>
                        {
                            j.HasKey("Principals_Id", "Tenants_Id");

                            j.ToTable("PrincipalTenant", "HostingModel");

                            j.HasIndex(new[] { "Tenants_Id" }, "IX_FK_PrincipalTenant_Tenant");
                        });
            });

            modelBuilder.Entity<RoutingDiscriminator>(entity =>
            {
                entity.ToTable("RoutingDiscriminators", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();
            });

            modelBuilder.Entity<Tenant>(entity =>
            {
                entity.ToTable("Tenants", "HostingModel");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();
            });

            modelBuilder.Entity<TenantInfo>(entity =>
            {
                entity.ToTable("TenantInfos", "HostingModel");

                entity.HasIndex(e => e.Tenant_Id, "IX_FK_TenantTenantInfo");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();

                entity.HasOne(d => d.Tenant)
                    .WithMany(p => p.TenantInfos)
                    .HasForeignKey(d => d.Tenant_Id)
                    .HasConstraintName("FK_TenantTenantInfo");
            });

            modelBuilder.Entity<UriPath>(entity =>
            {
                entity.ToTable("UriPaths", "HostingModel");

                entity.HasIndex(e => e.RoutingDiscriminatorId, "IX_FK_RoutingDiscriminatorUriPath");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.HasOne(d => d.RoutingDiscriminator)
                    .WithMany(p => p.UriPaths)
                    .HasForeignKey(d => d.RoutingDiscriminatorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_RoutingDiscriminatorUriPath");
            });

            modelBuilder.Entity<WebAPITenantInfo>(entity =>
            {
                entity.ToTable("WebAPITenantInfos", "HostingModel");

                entity.HasIndex(e => e.TenantInfoId, "IX_FK_TenantInfoWebAPITenantInfo");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedAt).HasColumnType("datetime");

                entity.Property(e => e.ObjectId).IsRequired();

                entity.HasOne(d => d.TenantInfo)
                    .WithMany(p => p.WebAPITenantInfos)
                    .HasForeignKey(d => d.TenantInfoId)
                    .HasConstraintName("FK_TenantInfoWebAPITenantInfo");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}