// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TheHorselessNewspaper.Schemas.HostingModel.Entities
{
    public partial class UriPath
    {
        public Guid Id { get; set; }
        public string AbsolutePath { get; set; }
        public string IsTenantDiscriminator { get; set; }
        public Guid RoutingDiscriminatorId { get; set; }
        public string ObjectId { get; set; }
        public string HostDisplayName { get; set; }

        public virtual RoutingDiscriminator RoutingDiscriminator { get; set; }
    }
}