/*
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Horseless.Keycloak.Admin.Rest.Api;
using Horseless.Keycloak.Admin.Rest.Model;
using Horseless.Keycloak.Admin.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Horseless.Keycloak.Admin.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing ClientInitialAccessPresentation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientInitialAccessPresentationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientInitialAccessPresentation
        //private ClientInitialAccessPresentation instance;

        public ClientInitialAccessPresentationTests()
        {
            // TODO uncomment below to create an instance of ClientInitialAccessPresentation
            //instance = new ClientInitialAccessPresentation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientInitialAccessPresentation
        /// </summary>
        [Fact]
        public void ClientInitialAccessPresentationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientInitialAccessPresentation
            //Assert.IsType<ClientInitialAccessPresentation>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RemainingCount'
        /// </summary>
        [Fact]
        public void RemainingCountTest()
        {
            // TODO unit test for the property 'RemainingCount'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

    }

}
