/*
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Horseless.Keycloak.Admin.Rest.Api;
using Horseless.Keycloak.Admin.Rest.Model;
using Horseless.Keycloak.Admin.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Horseless.Keycloak.Admin.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing SpiInfoRepresentation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpiInfoRepresentationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpiInfoRepresentation
        //private SpiInfoRepresentation instance;

        public SpiInfoRepresentationTests()
        {
            // TODO uncomment below to create an instance of SpiInfoRepresentation
            //instance = new SpiInfoRepresentation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpiInfoRepresentation
        /// </summary>
        [Fact]
        public void SpiInfoRepresentationInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpiInfoRepresentation
            //Assert.IsType<SpiInfoRepresentation>(instance);
        }


        /// <summary>
        /// Test the property 'Internal'
        /// </summary>
        [Fact]
        public void InternalTest()
        {
            // TODO unit test for the property 'Internal'
        }
        /// <summary>
        /// Test the property 'Providers'
        /// </summary>
        [Fact]
        public void ProvidersTest()
        {
            // TODO unit test for the property 'Providers'
        }

    }

}
