/*
 * Horseless Content API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TheHorselessNewspaper.CSharp.Rest.Client.OpenAPIDateConverter;

namespace TheHorselessNewspaper.CSharp.Rest.Model
{
    /// <summary>
    /// EdmIEdmEntityContainerElement
    /// </summary>
    [DataContract(Name = "EdmIEdmEntityContainerElement")]
    public partial class EdmIEdmEntityContainerElement : IEquatable<EdmIEdmEntityContainerElement>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ContainerElementKind
        /// </summary>
        [DataMember(Name = "containerElementKind", EmitDefaultValue = false)]
        public EdmEdmContainerElementKind? ContainerElementKind { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdmIEdmEntityContainerElement" /> class.
        /// </summary>
        /// <param name="containerElementKind">containerElementKind.</param>
        /// <param name="container">container.</param>
        public EdmIEdmEntityContainerElement(EdmEdmContainerElementKind? containerElementKind = default(EdmEdmContainerElementKind?), EdmIEdmEntityContainer container = default(EdmIEdmEntityContainer))
        {
            this.ContainerElementKind = containerElementKind;
            this.Container = container;
        }

        /// <summary>
        /// Gets or Sets Container
        /// </summary>
        [DataMember(Name = "container", EmitDefaultValue = false)]
        public EdmIEdmEntityContainer Container { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; private set; }

        /// <summary>
        /// Returns false as Name should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeName()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdmIEdmEntityContainerElement {\n");
            sb.Append("  ContainerElementKind: ").Append(ContainerElementKind).Append("\n");
            sb.Append("  Container: ").Append(Container).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdmIEdmEntityContainerElement);
        }

        /// <summary>
        /// Returns true if EdmIEdmEntityContainerElement instances are equal
        /// </summary>
        /// <param name="input">Instance of EdmIEdmEntityContainerElement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdmIEdmEntityContainerElement input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ContainerElementKind == input.ContainerElementKind ||
                    this.ContainerElementKind.Equals(input.ContainerElementKind)
                ) && 
                (
                    this.Container == input.Container ||
                    (this.Container != null &&
                    this.Container.Equals(input.Container))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ContainerElementKind.GetHashCode();
                if (this.Container != null)
                {
                    hashCode = (hashCode * 59) + this.Container.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
