/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContentEntitiesNavigationMenuItem } from '../model/models';
import { MvcProblemDetails } from '../model/models';


import { HorselessConfiguration }                                     from '../configuration';



export interface NavigationMenuItemRESTServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: HorselessConfiguration;

    /**
     * 
     * 
     * @param __tenant__ 
     * @param ContentEntitiesNavigationMenuItem 
     */
    contentEntitiesNavigationMenuItemRESTCreate(__tenant__: string, ContentEntitiesNavigationMenuItem?: ContentEntitiesNavigationMenuItem, extraHttpRequestParams?: any): Observable<ContentEntitiesNavigationMenuItem>;

    /**
     * 
     * 
     * @param objectId 
     * @param __tenant__ 
     */
    contentEntitiesNavigationMenuItemRESTGetByObjectId(objectId: string, __tenant__: string, extraHttpRequestParams?: any): Observable<ContentEntitiesNavigationMenuItem>;

    /**
     * 
     * 
     * @param __tenant__ 
     * @param pageSize 
     * @param pageNumber 
     * @param pageCount 
     */
    contentEntitiesNavigationMenuItemRESTGetByPageNumber(__tenant__: string, pageSize?: number, pageNumber?: number, pageCount?: number, extraHttpRequestParams?: any): Observable<Array<ContentEntitiesNavigationMenuItem>>;

    /**
     * 
     * 
     * @param contentCollectionId 
     * @param __tenant__ 
     * @param ContentEntitiesNavigationMenuItem 
     */
    contentEntitiesNavigationMenuItemRESTUpdate(contentCollectionId: string, __tenant__: string, ContentEntitiesNavigationMenuItem?: ContentEntitiesNavigationMenuItem, extraHttpRequestParams?: any): Observable<ContentEntitiesNavigationMenuItem>;

}
