/**
 * Horseless Content API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContentEntitiesTenant } from '../model/models';
import { HostingEntitiesTenant } from '../model/models';
import { MvcProblemDetails } from '../model/models';


import { HorselessConfiguration }                                     from '../configuration';



export interface TenantRESTServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: HorselessConfiguration;

    /**
     * 
     * 
     * @param objectId 
     * @param __tenant__ 
     */
    contentEntitiesTenantRESTGetByObjectId(objectId: string, __tenant__: string, extraHttpRequestParams?: any): Observable<ContentEntitiesTenant>;

    /**
     * 
     * 
     * @param __tenant__ 
     * @param pageSize 
     * @param pageNumber 
     * @param pageCount 
     */
    contentEntitiesTenantRESTGetByPageNumber(__tenant__: string, pageSize?: number, pageNumber?: number, pageCount?: number, extraHttpRequestParams?: any): Observable<Array<ContentEntitiesTenant>>;

    /**
     * 
     * 
     * @param contentCollectionId 
     * @param __tenant__ 
     * @param ContentEntitiesTenant 
     */
    contentEntitiesTenantRESTUpdate(contentCollectionId: string, __tenant__: string, ContentEntitiesTenant?: ContentEntitiesTenant, extraHttpRequestParams?: any): Observable<ContentEntitiesTenant>;

    /**
     * 
     * 
     * @param contentCollectionId 
     * @param __tenant__ 
     * @param updatedProperties 
     * @param ContentEntitiesTenant 
     */
    contentEntitiesTenantRESTUpdateProperties(contentCollectionId: string, __tenant__: string, updatedProperties?: Array<string>, ContentEntitiesTenant?: ContentEntitiesTenant, extraHttpRequestParams?: any): Observable<ContentEntitiesTenant>;

    /**
     * 
     * 
     * @param HostingEntitiesTenant 
     */
    hostingEntitiesTenantRESTCreate(HostingEntitiesTenant?: HostingEntitiesTenant, extraHttpRequestParams?: any): Observable<HostingEntitiesTenant>;

    /**
     * 
     * 
     * @param objectId 
     */
    hostingEntitiesTenantRESTGetByObjectId(objectId: string, extraHttpRequestParams?: any): Observable<HostingEntitiesTenant>;

    /**
     * 
     * 
     * @param pageSize 
     * @param pageNumber 
     * @param pageCount 
     */
    hostingEntitiesTenantRESTGetByPageNumber(pageSize?: number, pageNumber?: number, pageCount?: number, extraHttpRequestParams?: any): Observable<Array<HostingEntitiesTenant>>;

    /**
     * 
     * 
     * @param entityCollectionId 
     * @param HostingEntitiesTenant 
     */
    hostingEntitiesTenantRESTUpdate(entityCollectionId: string, HostingEntitiesTenant?: HostingEntitiesTenant, extraHttpRequestParams?: any): Observable<HostingEntitiesTenant>;

    /**
     * 
     * 
     * @param __tenant__ 
     * @param ContentEntitiesTenant 
     */
    tenantApiHorselessContentModelTenantCreatePost(__tenant__: string, ContentEntitiesTenant?: ContentEntitiesTenant, extraHttpRequestParams?: any): Observable<ContentEntitiesTenant>;

}
