//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema.Diagrams.SecondCut
{
    using System;
    using System.Collections.Generic;
    
    public partial class NugetPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NugetPackage()
        {
            this.AccessControlEntries = new HashSet<AccessControlEntry>();
            this.Principals = new HashSet<Principal1>();
        }
    
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string ObjectId { get; set; }
        public Nullable<bool> IsSoftDeleted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> PublishAt { get; set; }
        public Nullable<System.DateTime> UnPublishAt { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string PackageId { get; set; }
        public string PackageVersion { get; set; }
        public string PackageAuthor { get; set; }
        public string PackageSource { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string TenantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessControlEntry> AccessControlEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Principal1> Principals { get; set; }
    }
}
