//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema.Diagrams.SecondCut
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrincipalClaimContainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrincipalClaimContainer()
        {
            this.PrincipalClaims = new HashSet<PrincipalClaim>();
        }
    
        public System.Guid Id { get; set; }
        public string ObjectId { get; set; }
        public string DisplayName { get; set; }
        public string TenantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrincipalClaim> PrincipalClaims { get; set; }
        public virtual Principal1 Principal { get; set; }
    }
}
