export * from './contentCollection.service';
import { ContentCollectionService } from './contentCollection.service';
export * from './contentCollectionREST.service';
import { ContentCollectionRESTService } from './contentCollectionREST.service';
export * from './filesystemAsset.service';
import { FilesystemAssetService } from './filesystemAsset.service';
export * from './filesystemAssetREST.service';
import { FilesystemAssetRESTService } from './filesystemAssetREST.service';
export * from './holonym.service';
import { HolonymService } from './holonym.service';
export * from './holonymREST.service';
import { HolonymRESTService } from './holonymREST.service';
export * from './horselessContent.service';
import { HorselessContentService } from './horselessContent.service';
export * from './horselessSession.service';
import { HorselessSessionService } from './horselessSession.service';
export * from './horselessSessionREST.service';
import { HorselessSessionRESTService } from './horselessSessionREST.service';
export * from './jSONAsset.service';
import { JSONAssetService } from './jSONAsset.service';
export * from './jSONAssetREST.service';
import { JSONAssetRESTService } from './jSONAssetREST.service';
export * from './keycloakAuthentication.service';
import { KeycloakAuthenticationService } from './keycloakAuthentication.service';
export * from './meronym.service';
import { MeronymService } from './meronym.service';
export * from './meronymREST.service';
import { MeronymRESTService } from './meronymREST.service';
export * from './metadata.service';
import { MetadataService } from './metadata.service';
export * from './mimeTypeREST.service';
import { MimeTypeRESTService } from './mimeTypeREST.service';
export * from './navigationMenu.service';
import { NavigationMenuService } from './navigationMenu.service';
export * from './navigationMenuItem.service';
import { NavigationMenuItemService } from './navigationMenuItem.service';
export * from './navigationMenuItemREST.service';
import { NavigationMenuItemRESTService } from './navigationMenuItemREST.service';
export * from './navigationMenuREST.service';
import { NavigationMenuRESTService } from './navigationMenuREST.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './tenantInfoREST.service';
import { TenantInfoRESTService } from './tenantInfoREST.service';
export * from './tenantREST.service';
import { TenantRESTService } from './tenantREST.service';
export const APIS = [ContentCollectionService, ContentCollectionRESTService, FilesystemAssetService, FilesystemAssetRESTService, HolonymService, HolonymRESTService, HorselessContentService, HorselessSessionService, HorselessSessionRESTService, JSONAssetService, JSONAssetRESTService, KeycloakAuthenticationService, MeronymService, MeronymRESTService, MetadataService, MimeTypeRESTService, NavigationMenuService, NavigationMenuItemService, NavigationMenuItemRESTService, NavigationMenuRESTService, TenantService, TenantInfoRESTService, TenantRESTService];
